# -*- fill-column: 80; org-confirm-babel-evaluate: nil -*-

#+TITLE:     Assignment 14, Infinitesimal Calculus
#+AUTHOR:    Oleg Sivokon
#+EMAIL:     olegsivokon@gmail.com
#+DATE:      <2015-04-03 Fri>
#+DESCRIPTION: Fourth asssignment in the course Infinitesimal Calculus
#+KEYWORDS: Infinitesimal Calculus, Assignment, Limits of functions
#+LANGUAGE: en
#+LaTeX_CLASS: article
#+LATEX_HEADER: \usepackage[usenames,dvipsnames]{color}
#+LATEX_HEADER: \usepackage{commath}
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usetikzlibrary{shapes,backgrounds}
#+LATEX_HEADER: \usepackage{marginnote}
#+LATEX_HEADER: \usepackage{listings}
#+LATEX_HEADER: \usepackage{color}
#+LATEX_HEADER: \usepackage{enumerate}
#+LATEX_HEADER: \hypersetup{urlcolor=blue}
#+LATEX_HEADER: \hypersetup{colorlinks,urlcolor=blue}
#+LATEX_HEADER: \setlength{\parskip}{16pt plus 2pt minus 2pt}
#+LATEX_HEADER: \definecolor{codebg}{rgb}{0.96,0.99,0.8}
#+LATEX_HEADER: \definecolor{codestr}{rgb}{0.46,0.09,0.2}
#+LATEX_HEADER: \DeclareMathOperator{\Dom}{Dom}

#+BEGIN_SRC emacs-lisp :exports none
  (setq org-latex-pdf-process
          '("latexmk -pdflatex='pdflatex -shell-escape -interaction nonstopmode' -pdf -f %f")
          org-latex-listings t
          org-src-fontify-natively t
          org-latex-custom-lang-environments '((maxima "maxima"))
          org-babel-latex-htlatex "htlatex")
  
  (defmacro by-backend (&rest body)
      `(cl-case (when (boundp 'backend) (org-export-backend-name backend))
         ,@body))
#+END_SRC

#+RESULTS:
: by-backend

#+NAME: fname
#+HEADER: :var f="dummy"
#+BEGIN_SRC emacs-lisp :exports none
  (format "\"%s/%s\"" (file-name-directory (buffer-file-name)) f)
#+END_SRC

#+BEGIN_LATEX
  \definecolor{codebg}{rgb}{0.96,0.99,0.8}
  \lstnewenvironment{maxima}{%
    \lstset{backgroundcolor=\color{codebg},
      aboveskip=20pt,
      showstringspaces=false,
      frame=single,
      framerule=0pt,
      basicstyle=\ttfamily\scriptsize,
      columns=fixed}}{}
  }
  \makeatletter
  \newcommand{\verbatimfont}[1]{\renewcommand{\verbatim@font}{\ttfamily#1}}
  \makeatother
  \verbatimfont{\small}%
  \clearpage
#+END_LATEX

* Problems

** Problem 1
   1. Find the domain of $f$ defined as $f(x) = \sqrt{\tan x - 1}$.
   2. Find all values of $x$ in segment $[0, \pi]$, for which $\abs{\tan x} \leq \sin 2x}$.

*** Answer 1
    $\tan x > 1$ where $\frac{\pi}{4} < x \bmod \frac{\pi}{2} < \frac{\pi}{2}$.
    Since we assume that $f$ is real-valued, we cannot extract roots from negative numbers.
    
    Hence $\Dom(f) = \{x \in \mathbb{R} \; | \; \frac{\pi}{4} < x \bmod \frac{\pi}{2}
    < \frac{\pi}{2}\}$.
    
    #+NAME: prob1
    #+HEADER: :exports source
    #+HEADER: :var %out=fname(f="tangent_x.tex")
    #+BEGIN_SRC maxima :results output raw
      programmode: false;
      print (plot2d (tan(x),
          [x, -2 * %pi, 2 * %pi], [y, -3, 3],
          [gnuplot_pdf_term_command, 
           "set term cairolatex standalone pdf size 16cm,10.5cm"],
          [gnuplot_postamble,
           "set arrow from pi/4,-3 to pi/4,3 nohead
            set arrow from pi*5/4,-3 to pi*5/4,3 nohead
            set arrow from -2*pi,1 to 2*pi,1 nohead"],
          [ytics, 1, 1, 1], [xtics, 0, 1, 0],
          [label, ["${\\displaystyle \\frac{\\pi}{4}}$", 1.4, 2.4],
                  ["${\\displaystyle \\frac{5\\pi}{4}}$", 3.2, 2.4]],
          [title, "Tangent curve"], [pdf_file, %out]));
    #+END_SRC

    #+HEADER: :results raw file :exports results
    #+BEGIN_SRC emacs-lisp :var maxima-output=prob1(%out=fname(f="tangent_x.tex"))
      (let ((tex (replace-regexp-in-string
                  "[] ]+$" ""
                  (replace-regexp-in-string
                   "^\\s-+" ""
                   (car (reverse (split-string maxima-output "\n")))))))
        (shell-command
         (format "latexmk -pdflatex='pdflatex -shell-escape -interaction nonstopmode' -pdf -f %s"
                       tex))
        (format "%s.pdf" (file-name-sans-extension tex)))
    #+END_SRC

    #+ATTR_LATEX: :width 0.9\textwidth
    #+RESULTS:
    [[file:/home/wvxvw/Documents/uni/infinitesimal-calculus//tangent_x.pdf]]

*** Answer 2
    Both functions attain the same values at 0 and $\frac{\pi}{4}$.  But sine is
    a concave function and tanget is a convex function, thus tangent must be less
    than sine at this interval.  Tangent keeps increasing until $\frac{\pi}{2}$,
    while sine will be decreasing until $\frac{3\pi}{2}$, thus, on this interval
    tangent is greater than sine.  The functions meet again at $x=\pi$.
    
    #+NAME: prob2
    #+HEADER: :exports source
    #+HEADER: :var %out=fname(f="abstangent_x.tex")
    #+BEGIN_SRC maxima :results output raw
      programmode: false;
      gnuplot_pdf_command: %command;
      print(plot2d ([abs(tan(x)), sin(2 * x)],
          [x, -2 * %pi, 2 * %pi], [y, -1.5, 3],
          [gnuplot_pdf_term_command, 
           "set term cairolatex standalone pdf size 16cm,10.5cm"],
          [gnuplot_postamble,
           "set arrow from pi/4,-1.5 to pi/4,3 nohead
            set arrow from pi,-1.5 to pi,3 nohead
            set arrow from -2*pi,1 to 2*pi,1 nohead
            set key spacing 1.8 left bottom"],
          [xtics, 0, 1, 0], [ytics, 1, 1, 1],
          [label, ["${\\displaystyle \\frac{\\pi}{4}}$", 1.4, 2.1],
                  ["${\\displaystyle \\pi}$", 3.4, 2.1]],
          [title, "Tangent curve intersecting with sine curve"],
          [pdf_file, %out]));
    #+END_SRC

    #+HEADER: :results raw file :exports results
    #+BEGIN_SRC emacs-lisp :var maxima-output=prob2(%out=fname(f="abstangent_x.tex"))
      (let ((tex (replace-regexp-in-string
                  "[] ]+$" ""
                  (replace-regexp-in-string
                   "^\\s-+" ""
                   (car (reverse (split-string maxima-output "\n")))))))
        (shell-command
         (format "latexmk -pdflatex='pdflatex -shell-escape -interaction nonstopmode' -pdf -f %s"
                       tex))
        (format "%s.pdf" (file-name-sans-extension tex)))
    #+END_SRC

    #+ATTR_LATEX: :width 0.9\textwidth
    #+RESULTS:
    [[file:/home/wvxvw/Documents/uni/infinitesimal-calculus//abstangent_x.pdf]]

** Problem 2
   Let $f$, $g$ and $h$ be functions from $\mathbb{R}$ to $\mathbb{R}$.
   1. If $f \circ g = f \circ h$, does it follow $g = h$?
   2. If $f \circ g = f \circ h$, and $f$ is one-to-one, does it follow $g = h$?
   3. If $f \circ g = f \circ h$, and $f$ is onto, does it follow $g = h$?
   4. If $f \circ g$ is increasing, and $f$ is decreasing, does it follow that
      $g$ is increasing?
   5. If $f \circ g$ is increasing, and $f$ is one-to-one, does it follow that
      $g$ is monotonic?

*** Answer 3
    No, $g$ and $h$ are not necessarily equal.  Whenever co-domain of $f$
    doesn't contain some real number, $g$ and $h$ may differ in that input.
    For example, let $f(x) = 2x$, $g(x) = (x \bmod 2) + x$ and
    $h(x) = (x \bmod 2) * 2 + x$.  Because $f$ in this example will only
    generate even numbers, the $(x \bmod 2)$ term will always be zero,
    thus $f \circ g = f \circ h$, but, obviously, $g \neq h$.

*** Answer 4
    No, it isn't sufficient for $f$ to be one-to-one to ensure right-cancellation
    property under composition.  The example given in [[Answer 3]] is applicable
    in this case too since whenever $f(x) = f(y)$ so is $x = y$ (since multiplication
    does have the cancellation property).

*** Answer 5
    Yes, if $f$ is onto, then the composition is right-cancellable.  Suppose,
    for contradiction it wasn't, then for some $y$ $g(y) \neq h(y)$, but
    $y = f(x)$ (since by definition of a total function, every element in
    its co-domain has an element in its domain).  Hence $g(f(x)) \neq h(f(x))$,
    but we are given that $g \circ f = h \circ f$, which is a contradiction.
    Hence functions are equal.

*** Answer 6
    No, $g$ doesn't need to be increasing.  Put $g(x) = f(x) = -x$, both $f$
    and $g$ are decreasing but $f \circ g = Id$, which is an increasing function.

*** Anser 7
    No, $g$ is not necessarily monotonic.  Put $f(x) = x(-1)^x$ and $g(x) = \abs{x}$.
    Then $(f \circ g)(x) = \abs{x(-1)^x} = x\abs{(-1)^x} = x$.  $f \circ g$ is
    increasing, $f$ is one-to-one, but $g$ isn't monotonic: it decreases whenever
    $x$ is negative and increases whenever $x$ is positive.
    
** Problem 3
   1. Prove from $\epsilon-\delta$ definition of limit that 
      $\lim_{x \to 2}\sqrt{3x - 2} = 2$.
   2. Prove from $\epsilon-M$ definition of limit that 
      $\lim_{x \to \infty}\frac{x}{x+\sin x} = 1$.

*** Answer 8
    Recall the definition:
    #+BEGIN_QUOTE
    For all $\epsilon > 0$ there exists $\sigma > 0$ s.t. for all $x$ in
    $\Dom(f(x))$ which satisfy $0 < \abs{x - x_0} < \sigma$ the inequality
    $\abs{f(x) - L} < \epsilon$ holds.
    #+END_QUOTE

    Let $\epsilon$ be arbitrary real, put
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation*}
        \begin{aligned}
            &\abs{f(x) - L}          &< \epsilon                         &\iff \\
            &\abs{\sqrt{3x - 2} - 2} &< \epsilon                               \\
            &\textit{Suppose $\sqrt{3x - 2} - 2 > 0$}                          \\
          0 &< \sqrt{3x - 2} - 2     &< \epsilon                         &\iff \\
          0 &< \sqrt{3x - 2}         &< \epsilon + 2                     &\iff \\
          0 &< 3x - 2                &< (\epsilon + 2)^2                 &\iff \\
          0 &< 3x - 2                &< \epsilon^2 + 4\epsilon + 4       &\iff \\
          0 &< 3x - 6                &< \epsilon^2 + 4\epsilon           &\iff \\
          0 &< x - 2                 &< \frac{\epsilon^2 + 4\epsilon}{3}       \\
            &\textit{Similarly for $\sqrt{3x - 2} - 2 < 0$}                    \\
          0 &> \sqrt{3x - 2} - 2     &> -\epsilon                        &\iff \\
          0 &> \sqrt{3x - 2}         &> -\epsilon + 2                    &\iff \\
          0 &> 3x - 2                &> (-\epsilon + 2)^2                &\iff \\
          0 &> 3x - 2                &> \epsilon^2 - 4\epsilon + 4       &\iff \\
          0 &> 3x - 6                &> \epsilon^2 - 4\epsilon           &\iff \\
          0 &> x - 2                 &> \frac{\epsilon^2 - 4\epsilon}{3} &\iff \\
        \end{aligned}
      \end{equation*}
    #+END_SRC
    Hence, we can choose $\delta$ to be $\frac{\epsilon^2 - 4\epsilon}{3}$
    whenever $x < x_0$ and $\frac{\epsilon^2 + 4\epsilon}{3}$ whenever
    $x > x_0$, which completes the proof.

*** Answer 9
    Recall the definition:
    #+BEGIN_QUOTE
    For all $\epsilon > 0$ there exists $M > 0$ s.t. for all $x$ in
    $\Dom(f(x))$ $x > M$ implies $\abs{f(x) - L} < \epsilon$.
    #+END_QUOTE

    Let $\epsilon > 0$, then look for appropriate value for $x$:
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation*}
        \begin{aligned}
          &\abs{\frac{x}{x + \sin x} - 1}                   &< \epsilon &\iff \\
          &\abs{\frac{x}{x + \sin x} - \sin^2 x - \cos^2 x} &< \epsilon &\iff \\
          &\abs{\frac{x - \sin^2 x(x + \sin x) -
              \cos^2 x(x + \sin x)}{x + \sin x}}            &< \epsilon &\iff \\
          &\abs{\frac{x - x\sin^2 x - \sin^3 x -
              x\cos^2 x - \cos^2 x \sin x}{x + \sin x}}     &< \epsilon &\iff \\
          &\abs{\frac{x(1 - \sin^2 - \cos^2 x) -
              \sin x(\sin^2 x - \cos^2)}{x + \sin x}}       &< \epsilon &\iff \\
          &\abs{\frac{x(1 - 1) - \sin x(1)}{x + \sin x}}    &< \epsilon &\iff \\
          &\abs{\frac{-\sin x}{x + \sin x}}                 &< \epsilon \\
        \end{aligned}
      \end{equation*}
    #+END_SRC

    Assume $x > 0$:
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation*}
        \begin{aligned}
          &\frac{-\sin x}{x + \sin x} &< \epsilon &\iff \\
          &-\sin x                    &< \epsilon(x + \sin x) &\iff \\
          &-\sin x                    &< \epsilon x + \epsilon \sin x &\iff \\
          &-\epsilon x                &< \sin x + \epsilon \sin x &\iff \\
          &-x                         &< \frac{\sin x + \epsilon \sin x}{\epsilon} &\iff \\
          &x                          &> \frac{\sin x(1 + \epsilon)}{\epsilon}
        \end{aligned}
      \end{equation*}
    #+END_SRC

    Put $M = \max\left(0, \frac{\sin x(1 + \epsilon)}{\epsilon}\right)$. If $x > M$, then
    $x > 0$ and $x > \frac{\sin x(1 + \epsilon)}{\epsilon}$, hence:
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation*}
        \begin{aligned}
          &x                              &> \frac{\sin x(1 + \epsilon)}{\epsilon} \\
          &\hdots \textit{Reverse the calculations above} \\
          &\frac{-\sin x}{x + \sin x}     &< \epsilon \\
          &\hdots \\
          &\abs{\frac{x}{x + \sin x} - 1} &< \epsilon.
        \end{aligned}
      \end{equation*}
    #+END_SRC
    Which completes the proof.

** Problem 4
   1. Let $f$ be a function defined in the neighborhood of $x_0$.
      Express ``$f$ doesn't have a limit at $x_0$'' using:
      + $\epsilon-\sigma$ language.
      + Using Heine definition of limit (for sequences).
        
   2. Prove that $f(x) = \frac{x}{x - \lfloor x \rfloor}$ doesn't have
      a finite limit at $x \to 0$ in the following ways:
      + By using $\epsilon-\sigma$ definition given above.
      + By using Heine definition of limit (also given above).

*** Answer 10
    
*** Answer 11

** Problem 5
   Find limits of:
   1. $\lim_{x \to 0}\frac{1 - \cos x}{x \sin x}$.
   2. $\lim_{x \to 0}\frac{x + 7x^3}{x^3 - 2x^4}$.
   3. $\lim_{x \to 0}\frac{x^2 - 1}{2x^3 - x^2 - x}$.
   4. $\lim_{x \to 0}(\sqrt{1 + x + x^2} - \sqrt{1 - x + x^2})$.
   5. $\lim_{x \to k}\lfloor x \rfloor \tan \frac{\pi x}{2}$.
