# -*- fill-column: 80; org-confirm-babel-evaluate: nil -*-

#+TITLE:     Assignment 11, Infinitesimal Calculus
#+AUTHOR:    Oleg Sivokon
#+EMAIL:     olegsivokon@gmail.com
#+DATE:      <2015-03-14 Sat>
#+DESCRIPTION: First asssignment in the course Infinitesimal Calculus
#+KEYWORDS: Infinitesimal Calculus, Assignment, Properties of Numbers
#+LANGUAGE: en
#+LaTeX_CLASS: article
#+LATEX_HEADER: \usepackage[usenames,dvipsnames]{color}
#+LATEX_HEADER: \usepackage[backend=bibtex, style=numeric]{biblatex}
#+LATEX_HEADER: \usepackage{commath}
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usetikzlibrary{shapes,backgrounds}
#+LATEX_HEADER: \usepackage{marginnote}
#+LATEX_HEADER: \usepackage{listings}
#+LATEX_HEADER: \usepackage{color}
#+LATEX_HEADER: \usepackage{enumerate}
#+LATEX_HEADER: \hypersetup{urlcolor=blue}
#+LATEX_HEADER: \hypersetup{colorlinks,urlcolor=blue}
#+LATEX_HEADER: \addbibresource{bibliography.bib}
#+LATEX_HEADER: \setlength{\parskip}{16pt plus 2pt minus 2pt}
#+LATEX_HEADER: \definecolor{codebg}{rgb}{0.96,0.99,0.8}
#+LATEX_HEADER: \definecolor{codestr}{rgb}{0.46,0.09,0.2}

#+BEGIN_SRC emacs-lisp :exports none
(setq org-latex-pdf-process
        '("latexmk -pdflatex='pdflatex -shell-escape -interaction nonstopmode' -pdf -bibtex -f %f")
        org-latex-listings t
        org-src-fontify-natively t
        org-babel-latex-htlatex "htlatex")
(defmacro by-backend (&rest body)
    `(cl-case (when (boundp 'backend) (org-export-backend-name backend))
       ,@body))
#+END_SRC

#+RESULTS:
: by-backend

#+BEGIN_LATEX
  \lstset{ %
    backgroundcolor=\color{codebg},
    basicstyle=\ttfamily\scriptsize,
    breakatwhitespace=false,         % sets if automatic breaks should only happen at whitespace
    breaklines=false,
    captionpos=b,                    % sets the caption-position to bottom
    commentstyle=\color{mygreen},    % comment style
    framexleftmargin=10pt,
    xleftmargin=10pt,
    framerule=0pt,
    frame=tb,                        % adds a frame around the code
    keepspaces=true,                 % keeps spaces in text, useful for keeping indentation of code (possibly needs columns=flexible)
    keywordstyle=\color{blue},       % keyword style
    showspaces=false,                % show spaces everywhere adding particular underscores; it overrides 'showstringspaces'
    showstringspaces=false,          % underline spaces within strings only
    showtabs=false,                  % show tabs within strings adding particular underscores
    stringstyle=\color{codestr},     % string literal style
    tabsize=2,                       % sets default tabsize to 2 spaces
  }
#+END_LATEX

\clearpage

* Problems

** Problem 1
   1. Prove that for any natural number $n$ it holds that:
      #+HEADER: :exports results
      #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
      #+BEGIN_SRC latex
        \begin{equation*}
          4^n \geq {2n \choose n}.
        \end{equation*}
      #+END_SRC
   2. Prove by induction, or in any other way, that for any natural number $n$
      it holds that:
      #+HEADER: :exports results
      #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
      #+BEGIN_SRC latex
        \begin{equation*}
           {2n \choose n} \geq \frac{4^n}{2n+1}.
        \end{equation*}
      #+END_SRC

*** Answer 1
    *Discussion:* The idea behind the proof is to show that ${2n \choose n}$ is
    a term in the binomial expansion representing $4^n$.  Since all other terms
    in this expansion will be non-negative, then $4^n$ will be at least as big
    as ${2n \choose n}$.

    *Proof:* Put $4^n=(1+1)^{2n}$, using binomial formula obtains:
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{align*}
        (1+1)^{2n} &= \sum_{k=0}^{2n} {2n \choose k}1^{2n}1^{2n-k} \\
                  &= {2n \choose n} + \sum_{k=0, k\neq n}^{2n} {2n \choose k}.
      \end{align*}
    #+END_SRC
    We know that ${2n \choose n}$ is a term of binomial expansion because we
    know that $k_i \leq 2n$, which implies that since $k_i, n$ are natural numbers,
    there exists $k_i = n$.  Besides, there might exist other terms in binomial
    expansion which are guaranteed to be non-negative.  Hence,
    $4^n \geq {2n \choose n}$.

*** Answer 2
    *Discussion:* In order to make the proof a little less verbose, I will prove
    a stronger claim, viz. ${2n \choose n} \geq \frac{4^n}{2n}$.  Since $n$ is
    positive, $2n < 2n +1$, hence $\frac{4^n}{2n} > \frac{4^n}{2n + 1}$.  The
    proof will proceed by induction on $n$.  First I will find a factor s.t.
    multiplying it with $S_{n-1}$ I will obtain $S_n$, and then multiply it
    with the $\frac{4^n}{2n}$ to show that it will necessary be at leas as large
    as $\frac{4^{n+1}}{2(n+1)}$.

    *Proof:* Using mathematical induction, let's first prove the base step,
    where $n=1$:
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{align*}
        { 2*1 \choose 1}    &\geq \frac{4^1}{2*1} \iff \\
        \frac{2!}{1!(2-1)!} &\geq \frac{4}{2} \iff \\
        \frac{2}{1}         &\geq 2 \iff \\
        2                   &\geq 2.
      \end{align*}
    #+END_SRC

    Now, to the inductive step (for $n>1$), some useful simplification first:
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation}
        \begin{aligned}
          {2n \choose n} &= \frac{(2n)!}{n!(2n - n)!} \\
          &= \frac{(2n!)}{n!n!}. \\
        \end{aligned}
        \label{eq:base}
      \end{equation}
    #+END_SRC
    Invoking inductive hypothesis ${2(n+1) \choose (n+1)} \geq \frac{4^n}{2n}$:
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation}
        \begin{aligned}
          {2(n+1) \choose n+1} &= \frac{(2(n+1))!}{(n+1)!(2(n+1) - n+1)!} \\
          &= \frac{(2n!)(2n+1)(2n+2)}{n!(n+1)n!(n+1)} \\
          &= \frac{(2n!)(2n+1)2(n+1)}{n!(n+1)n!(n+1)} \\
          &= \frac{(2n!)(2n+1)2}{n!n!(n+1)}.
        \end{aligned}
        \label{eq:step}
      \end{equation}
    #+END_SRC
    Dividing $\ref{eq:step}$ by $\ref{eq:base}$ gives us the factor $\frac{(2n+1)2}{(n+1)}$. Thus:
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{align*}
        \frac{(2n+1)2}{n+1} \times \frac{4^n}{2n} &\geq \frac{4^{n+1}}{2(n+1)} \\
        \frac{(2n+1)2*4^n}{2n(n+1)} &\geq \frac{4^{n+1}}{2(n+1)} \\
        \frac{(2n+1)2*4^n}{n} &\geq 4^{n+1} \\
        \frac{(2n+1)2*4^n}{n} &\geq 4^{n}*4 \\
        \frac{(2n+1)2}{n} &\geq 4 \\
        \frac{4n+2}{n} &\geq 4 \\
        4 + \frac{2}{n} &\geq 4 \\
      \end{align*}
    #+END_SRC
    Since $n > 1$, $\frac{2}{n}$ is positive, hence the inequality holds.
    This completes the inductive step.  Hence, by using mathematical induction
    the proof is complete.

** Problem 2
   1. Given $k, l \in \mathbb{N}$, prove that $a=k+l\sqrt{2}$ is irrational.
   2. Prove that for every natural number $n$ it holds that:
      #+HEADER: :exports results
      #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
      #+BEGIN_SRC latex
        \begin{equation*}
           \sum_{i=0}^n \sqrt{2}^i
        \end{equation*}
      #+END_SRC
      is irrational.

*** Answer 3
    *Discussion:* One way to see that summation of rational with irrational
    cannot produce a rational number is through invoking field axioms: summation
    must send the sum to the field of rationals, which would imply that the
    inverses of summands must be rationals too.  This would also require summands
    to be rationals, but that's not possible.
    
    *Proof:* Suppose, for contradiction that $k+l\sqrt{2}=a$ is rational, then
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation*}
        \begin{aligned}
          k+l\sqrt{2} &= a & \textrm{Given} \\
          k+(-k)+l\sqrt{2} &= a-k &
          \textrm{$k$ must have additive inverse in $\mathbb{Q}$} \\
          0+l\sqrt{2} &= a-k \\
          l^{-1}l\sqrt{2} &= l^{-1}(a-k) &
          \textrm{$l$ must have multiplicative inverse in $\mathbb{Q}$} \\
          1\sqrt{2} &= l^{-1}(a-k) \\
          \sqrt{2} &= l^{-1}(a-k).
        \end{aligned}
      \end{equation*}
    #+END_SRC
    
    $l^{-1}, q$ and $k$ are all rationals, rationals are closed under multiplication
    and addition, hence $l^{-1}(q-k)$ must be rational, but $\sqrt{2}$ is not.
    Contradiction.  Hence $a=k+l\sqrt{2}$ is irrational.
    
*** Answer 4
    *Discussion:* The way to see that this statement is true is to divide the sequence
    into odd and even terms.  All even terms will produce rationals (even poverse of
    square root of two will be rational).  While all odd terms will produce irrational
    numbers (a product of even number of square roots of two will give a rational, but
    them multiplied with an irrational number will give an irrational).  Since $n$
    must be at least one (and thus we are guaranteed to have at least one odd term in
    this sequence), the sum of the sequence will always be irrational.

    *Proof:* Let's rewrite this sum as two sums of the form:
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation*}
        \sum_{i=0}^{\lfloor n/2 \rfloor} \sqrt{2}^{2i} +
        \sum_{i=0}^{\lfloor (n+1)/2 \rfloor} \sqrt{2}^{2i+1}.
      \end{equation*}
    #+END_SRC
    It is easy to see that the first term is a sum of powers of 2, viz:
    $\sqrt{2}^2+\sqrt{2}^4+\hdots+\sqrt{2}^{\lfloor n/2 \rfloor}$, which is just
    $2+4+\hdots+2^{\lfloor n/2-1 \rfloor}$.  Similarly, the terms of the other
    sum can be expressed as $\sqrt{2}^1+\sqrt{2}^3+\hdots+\sqrt{2}^{\lfloor
    (n+1)/2 \rfloor}$.

    Let's give names to the sequences we outlined: $S_1=\sum_{i=0}^{\lfloor n/2
    \rfloor} \sqrt{2}^{2i}$ and $S_2=\sum_{i=0}^{\lfloor (n+1)/2 \rfloor}
    \sqrt{2}^{2i+1}$.  Now, for contradiction, assume $S_2$ to be rational.
    Then let's define $\div$ to be the element-wise division of sequences,
    i.e. for sequences $A$ and $B$ of length $n$, $\div$ is defined to be:
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation*}
        \sum_{i=0}^n \frac{A_i}{B_i}.
      \end{equation*}
    #+END_SRC
    It's easy to see that if all elements of $A$ and $B$ are rational, then $A
    \div B$ is rational too (because we only used addition and multiplication,
    which are known to be closed over rationals).

    Observe that $S_2 \div S_3=\sum_{i=0}^{\lfloor (n+1)/2 \rfloor} \sqrt{2}$,
    i.e. a sum of $n/2$ square roots of 2, which is the same as $n/2*\sqrt{2}$,
    but we've just showed that the product of a rational and irrational cannot be
    rational (in previous question). Hence $S_2$ must be irrational, contrary to
    assumed.  Hence it must be that $\sum_{i=0}^n \sqrt{2}^i$ is irrational.
    This completes the proof.

** Problem 3
   1. Given real numbers $a$ and $b$ prove that if
      #+HEADER: :exports results
      #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
      #+BEGIN_SRC latex
        \begin{equation*}
           \frac{\abs{a}}{2}>\abs{b-\frac{a}{2}},
        \end{equation*}
      #+END_SRC
      then
      #+HEADER: :exports results
      #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
      #+BEGIN_SRC latex
        \begin{equation*}
           \abs{b-a}<\abs{a}.
        \end{equation*}
      #+END_SRC

*** Answer 5
    *Discussion:* The proof will be based on invariance of order under multiplication,
    in particular, it will rely on the fact that $\abs{x} < \abs{y} \iff x^2 < y^2$.
    This will allow us to solve the inequality without splitting it into several
    cases.
       
    *Proof:* First, let's simplify the expression:
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation*}
        \begin{aligned}
          \frac{\abs{a}}{2} &> \abs{b-\frac{a}{2}} 
          & \textrm{Given} \\
          \abs{a}           &> 2\abs{b-\frac{a}{2}}
          & \textrm{Invariance of order under multiplication} \\
          \abs{a}           &> \abs{2b-a}
          & \textrm{Distributivity of multiplication over addition} \\
          \abs{2b-a}        &< \abs{a} \\
          \abs{2b-a}^2      &< \abs{a}^2
          & \textrm{Invariance under exponentiation} \\
          (2b-a)^2          &< a^2
          & \textrm{Squares are always positive} \\
          4b^2 - 4ba + a^2  &< a^2 \\
          4b^2 - 4ba        &< 0 \\
          4b^2              &< 4ba \\
          b^2               &< ba
          & \textrm{Invariance under multiplication}
        \end{aligned}
      \end{equation*}
    #+END_SRC

    Next, let's perform similar operations on $\abs{b-a}<\abs{a}$
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation*}
        \begin{aligned}
          \abs{b - a}     &< \abs{a}
          & \textrm{Given} \\
          \abs{b - a}^2   &< \abs{a}^2
          & \textrm{Invariance under exponentiation} \\
          (b - a)^2       &< a^2
          & \textrm{Squares are always positive} \\
          b^2 - 2ba + a^2 &< a^2 \\
          b^2 - 2ba       &< 0 \\
          b^2             &< 2ba.
          \end{aligned}
      \end{equation*}
    #+END_SRC
    
    From transitivity of order it follows that $b^2 < ba < 2ba$, i.e.
    $b^2 < 2ba$, but this is exactly the condition we set out to prove in the
    very beginning.  Thus, the proof is complete.
    
** Problem 4
   Given $a, b, c \in \mathbb{R}$,
   1. Prove that if $a > 0$ and $a + b > a + c$, then $b > c$.
   2. Prove that if $a > 0$ and $ab > ac$, then $b > c$.
   3. Prove that $\abs{a} > \abs{b}$ iff $a^2 > b^2$.
   4. Prove that if $b > c$ and $\abs{a-b} > \abs{a-c}$, then $b > a$.
   5. Show (my means of example) that from $b > c$ and $b > a$ it doesn't
      follow that $\abs{a-b} > \abs{a-c}$.

*** Answer 6
    *Proof:* The proof is simple algebra relying on invariance of order
    under addition:
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation*}
        \begin{aligned}
          a+b    &> a+c    & \textrm{Given} \\
          -a+a+b &> -a+a+c & \textrm{Invariance under addition} \\
          0+b    &> 0+c    & \textrm{Devinition of inverse} \\
          b      &> c      & \textrm{Devinition of inverse}
        \end{aligned}
      \end{equation*}
    #+END_SRC
    
*** Answer 7
    *Proof:* The proof is simple algebra relying on invariance of order
    under multiplication:
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation*}
        \begin{aligned}
          ab       &> ac      & \textrm{Given} \\
          a^{-1}ab &> a^{-1}ac & \textrm{Invariance under multiplication} \\
          1b       &> 1c      & \textrm{Devinition of inverse} \\
          b        &> c       & \textrm{Devinition of inverse}
        \end{aligned}
      \end{equation*}
    #+END_SRC
    
*** Answer 8
    *Proof:* first I will prove the implies part, i.e.
    $\abs{a} > \abs{b} \implies a^2 > b^2$, and then the
    $\abs{a} > \abs{b} \impliedby a^2 > b^2$:
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation*}
        \begin{aligned}
          \abs{a}        &> \abs{b}      & \textrm{Given} \\
          \abs{a}\abs{a} &> \abs{a}\abs{b} & \textrm{Invariance under multiplication} \\
          a^2            &> \abs{ab} & \textrm{Simple algebra} \\
          \abs{a}        &> \abs{b} & \textrm{Reiteration of the given} \\
          \abs{a}\abs{b} &> \abs{b}\abs{b} & \textrm{Invariance under multiplication} \\
          \abs{ab}       &> b^2 & \textrm{Simple algebra} \\
          a^2 > \abs{ab} &> b^2 & \textrm{Reusing derivation from step 3} \\
          a^2            &> b^2 & \textrm{By transitivity of order}
        \end{aligned}
      \end{equation*}
    #+END_SRC
    The converse proof:
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation*}
        \begin{aligned}
          a^2 > b^2
          \abs{a}\abs{a} &> \abs{b}\abs{b} & \textrm{Simple algebra} \\
          \abs{a}\abs{a} - \abs{b}\abs{b} &> 0 & \textrm{Simple algebra} \\
          \abs{a}(\abs{b} + c) - \abs{b}\abs{b} &> 0 & \textrm{Define $c=\abs{a}-\abs{b}$} \\
          \abs{a}\abs{b} + \abs{a}c - \abs{b}\abs{b} &> 0 \\
          (\abs{a} - \abs{b})\abs{b} + \abs{a}c &> 0 \\
          (\abs{a} - \abs{b})\abs{b} &> -\abs{a}c \\
          (\abs{a} - \abs{b})\abs{b} &> -\abs{a}(\abs{a}-\abs{b})
          & \textrm{Recall $c=\abs{a}-\abs{b}$} \\
          \abs{b} &> -\abs{a} & \textrm{Invariance under multiplication} \\
          -\abs{a} &< \abs{b} \\
          \abs{a} &> \abs{b} & \textrm{Multiplying by $-1$}
        \end{aligned}
      \end{equation*}
    #+END_SRC
    Both the ``if'' part and its converse have been proved, thus the proof is complete.
    
*** Answer 9
    *Proof:* For the sake of diversity, this proof will rely on axioms rather
    than algebraic manipulations.  Perusing the first axiom of order, we know
    that either one of the three holds: $c < a$, $c = a$ or $c > a$.  Consider
    $c < a$.  We are given that the distance from $a$ to $b$ is greater than the
    distance from $a$ to $c$.  This means that $b$ cannot lie between $a$ and
    $c$ (recall the triangle inequality), neither can it lie between $c$ and $a$
    if $a = c$, hence $b > a$.

    Consider now $c > a$, we are given that $b > c$, thus, by transitivity of
    order we conclude that $b > c > a$ and in particular $b > a$.  This
    completes the proof.

*** Answer 10
    Any combination of $a, b$ and $c$ s.t. $c > a > b$ and $a - c > b - a$ will
    satisfy the requirement, and in particular $c=1, a=3, b=4$ as is easy to
    see: $\abs{a-b}>\abs{a-c}\implies\abs{3-4}>\abs{3-1}\implies 1 > 2$.
    A way to see why this is true is to picture the number line, where
    the distance is measured from the central point $a$ to two points on
    the left and on the right of it.  We aren't constrained in any way as
    to which side should be bigger, thus we can certainly obtain the one
    that fits the requirement.

** Problem 5
   Solve the equation:
   #+HEADER: :exports results
   #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
   #+BEGIN_SRC latex
     \begin{equation*}
        \lfloor \abs{x+1}-\abs{x-1} \rfloor = x.
     \end{equation*}
   #+END_SRC
   
*** Answer 11

** Problem 6
   *Definition:* set $A$ of real numbers is called *dense in interval* $I$ if
   for every $x, y \in I$ s.t. $x < y$ there exists $a \in A$ such that
   $x < a < y$.

   1. Let $A$ be dense in interval $[0,1]$, prove that set 
      $B=\{na|a \in A, n \in \mathbb{N}\}$ is dense in interval $[0, \infty)$.
   2. Let $A=\mathbb{R}$, prove that $A$ isn't dense in $I$ iff exists an
      open interval $(x, y)$ in $I$, such that $A \cap (x, y) = \emptyset$.
   3. Let $A$ be the real numbers in interval $[0,1]$, prove that the set
      $C=\{\frac{a+1}{n^2} | a \in A, n \in \mathbb{N}\}$ isn't dense in
      $[0,1]$.

*** Answer 12
*** Answer 13
*** Answer 14
