# -*- fill-column: 80; org-confirm-babel-evaluate: nil -*-

#+TITLE:     Assignment 12, Infinitesimal Calculus
#+AUTHOR:    Oleg Sivokon
#+EMAIL:     olegsivokon@gmail.com
#+DATE:      <2015-04-03 Fri>
#+DESCRIPTION: Second asssignment in the course Infinitesimal Calculus
#+KEYWORDS: Infinitesimal Calculus, Assignment, Definition of Limits
#+LANGUAGE: en
#+LaTeX_CLASS: article
#+LATEX_HEADER: \usepackage[usenames,dvipsnames]{color}
#+LATEX_HEADER: \usepackage[backend=bibtex, style=numeric]{biblatex}
#+LATEX_HEADER: \usepackage{commath}
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usetikzlibrary{shapes,backgrounds}
#+LATEX_HEADER: \usepackage{marginnote}
#+LATEX_HEADER: \usepackage{listings}
#+LATEX_HEADER: \usepackage{color}
#+LATEX_HEADER: \usepackage{enumerate}
#+LATEX_HEADER: \hypersetup{urlcolor=blue}
#+LATEX_HEADER: \hypersetup{colorlinks,urlcolor=blue}
#+LATEX_HEADER: \addbibresource{bibliography.bib}
#+LATEX_HEADER: \setlength{\parskip}{16pt plus 2pt minus 2pt}
#+LATEX_HEADER: \definecolor{codebg}{rgb}{0.96,0.99,0.8}
#+LATEX_HEADER: \definecolor{codestr}{rgb}{0.46,0.09,0.2}

#+BEGIN_SRC emacs-lisp :exports none
(setq org-latex-pdf-process
        '("latexmk -pdflatex='pdflatex -shell-escape -interaction nonstopmode' -pdf -bibtex -f %f")
        org-latex-listings t
        org-src-fontify-natively t
        org-babel-latex-htlatex "htlatex")
(defmacro by-backend (&rest body)
    `(cl-case (when (boundp 'backend) (org-export-backend-name backend))
       ,@body))
#+END_SRC

#+RESULTS:
: by-backend

#+BEGIN_LATEX
  \lstset{ %
    backgroundcolor=\color{codebg},
    basicstyle=\ttfamily\scriptsize,
    breakatwhitespace=false,         % sets if automatic breaks should only happen at whitespace
    breaklines=false,
    captionpos=b,                    % sets the caption-position to bottom
    commentstyle=\color{mygreen},    % comment style
    framexleftmargin=10pt,
    xleftmargin=10pt,
    framerule=0pt,
    frame=tb,                        % adds a frame around the code
    keepspaces=true,                 % keeps spaces in text, useful for keeping indentation of code (possibly needs columns=flexible)
    keywordstyle=\color{blue},       % keyword style
    showspaces=false,                % show spaces everywhere adding particular underscores; it overrides 'showstringspaces'
    showstringspaces=false,          % underline spaces within strings only
    showtabs=false,                  % show tabs within strings adding particular underscores
    stringstyle=\color{codestr},     % string literal style
    tabsize=2,                       % sets default tabsize to 2 spaces
  }
#+END_LATEX

\clearpage

* Problems

** Problem 1
   1. Prove from definition $\epsilon-N$:
      #+HEADER: :exports results
      #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
      #+BEGIN_SRC latex
        \begin{equation*}
          \lim_{n \to \infty} \frac{n^2}{n^2-1} = L.
        \end{equation*}
      #+END_SRC
   2. Prove from definition $M-N$:
      #+HEADER: :exports results
      #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
      #+BEGIN_SRC latex
        \begin{equation*}
           \lim_{n \to \infty} \frac{n^2-n}{n+2} = \infty.
        \end{equation*}
      #+END_SRC
   3. Formulate $\lim_{n \to \infty} a_n = \infty$ in terms of $M-N$ definition.
   4. Prove using the formulation from (3) that:
      #+HEADER: :exports results
      #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
      #+BEGIN_SRC latex
        \begin{equation*}
           \lim_{n \to \infty} (n\sqrt{2} + (-1)^n \lfloor \sqrt{n} \rfloor) = \infty.
        \end{equation*}
      #+END_SRC

*** Answer 1
    Recall the definition:

    #+BEGIN_QUOTE
    Let $(a_n)^{\infty}_{n=1}$ be a sequence, $L$ be a real number.  The
    *sequence $(a_n)$ converges to $L$* if for all $\epsilon > 0$ almost all
    elements of the sequence are in the $\epsilon$-neighborhood of $L$.  In such
    a case we will say $L$ is the *limit of sequence $(a_n)$*.
    #+END_QUOTE

    To be honest, I don't know what this question is asking me to do.  How can
    I prove something which is already given in the description of a question?
    Anyways, I followed the examples in the book, and here is what I think the
    answer might look like.  Sorry, if this is not what you expect.
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation*}
        \begin{aligned}
          \epsilon &> 1 \implies & \textit{From definition of reals} \\
          \epsilon &> \frac{n^2-1}{n^2-1} \implies & \textit{Provided $n \neq 1$} \\
          \epsilon' &> \frac{1}{n^2-1} \implies & \textit{From Archimedian property} \\
          \epsilon + \epsilon' &> \frac{n^2}{n^2-1} \implies
          & \textit{Provided $\epsilon'' = \epsilon' + \epsilon$} \\
          \epsilon'' &> \abs{\frac{n^2}{n^2-1} - L} & \textit{Provided $0 \leq L \leq 1$}
        \end{aligned}
      \end{equation*}
    #+END_SRC
    Which completes the ``proof''.

*** Answer 2
    First, recall the definition:

    #+BEGIN_QUOTE
    We will say that the sequence $(a_n)^{\infty}_{n=1}$ *tends to infinity*, and
    write $\lim_{n \to \infty} a_n = \infty$, if for every real number $M$ there
    exists a natural number $N$ such that for all $n > N$ it holds that $a_n > M$.
    #+END_QUOTE

    We can start by finding a more convenient formulat to work with, for instance:
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation*}
        \begin{aligned}
          M &= \frac{n^2 - n}{n + 2} \\
          &= \frac{n(n - 1)}{n + 2} \\
          &= \frac{n(n + 2)}{n + 2} - \frac{3n}{n + 2} \\
          &< n - \frac{3n}{n} \\
          &= n - 3.
        \end{aligned}
      \end{equation*}
    #+END_SRC

    Now, put $N = M + 3$. Thus for every $M$, $a_n$ is greater than $M$ whenver
    $n \geq M + 3$.

*** Answer 3
    I'm confused by this question in the same measure I'm confused by the previous
    one.  I don't know what do you want me to prove here.  There can be different
    reasons for why some sequence doesn't tend to infinity.  It could be because
    it is a divergent series, or because it converges to some real limit, or
    because it tends to negative infinity.  I can formally negate the statement
    but I don't think this negation is useful.
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation*}
        \begin{aligned}
          \lnot \forall M \in \mathbb{R} : \exists N \in \mathbb{N} :
          \forall n \in \mathbb{N} : (n > N \implies a_n > M) \\
          \textit{Alternatively:} \\
          \exists M \in \mathbb{R} : \forall N \in \mathbb{N} :
          \exists n \in \mathbb{N} : (n > N \implies a_n \leq M)
        \end{aligned}
      \end{equation*}
    #+END_SRC

*** Answer 4
    It is easy to see that the given sequence is divergent.  It has two limit
    points, where one is at infinity and another one is at zero.  Since I need
    to reuse the $M-N$ rule, I will restate this clame in terms of this rule.
    There exists a real number $M$, such that for every natural number $N$,
    there exists a natural number $n$, such that whenever $n > N$, $a_n \leq M$.
    Put $M = 2$, then $a_n = 2(\sqrt{2} + \lfloor \sqrt{2} \rfloor)$.  Now, no matter
    the $N$, we can always choose $n$ to be odd, which will give us:
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation*}
        \begin{aligned}
          2\sqrt{2} + \lfloor 2\sqrt{2} \rfloor \geq n\sqrt{2} - \lfloor n\sqrt{2} \rfloor \\
          \textit{For every $n > 2$} \\
          2 * 2 + \lfloor 2 * 2 \rfloor \geq n 2 - \lfloor n * 2 \rfloor \\
          \textit{By axiom of order} \\
          8 \geq 0.
        \end{aligned}
      \end{equation*}
    #+END_SRC

** Problem 2
   Calculate the limits of the expression given above, or prove that the limtes don't
   exists:

   #+HEADER: :exports results
   #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
   #+BEGIN_SRC latex
     \begin{eqnarray}
       \lim_{n \to \infty} \sqrt{1 + \frac{a}{n}} \\
       \lim_{n \to \infty} \sqrt{n + a} * \sqrt{n + b} - n \\
       \lim_{n \to \infty} \frac{n^7 - 2n^4 - 1}{n^4 - 3n^6 + 7} \\
       \lim_{n \to \infty} \Big(\frac{n}{n + 1} \sum_{k=1}^n \frac{k}{k+1} \Big)
     \end{eqnarray}
   #+END_SRC

*** Answer 5
    Using ``sandwich'' rule we can show that:
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation*}
        \sqrt{1} < \sqrt{1 + \frac{a}{n}} < 1 + \frac{a}{n}
      \end{equation*}
    #+END_SRC
    Provided $a$ is non-negative and isn't equal to $n$.  The limit of $\sqrt{1}$
    is trivially 1.  The limit of $1 + \frac{a}{n}$ is the sum of the limits of
    1 and $\frac{a}{n}$, where the former is the limit of a constant (1), and the
    later is zero.  Thus the value is ``sandwiched'' between 1 and 1, hence it
    must be 1.

*** Answer 6
    Let's generalize the expression to reuse the previous case:
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation*}
        \begin{aligned}
          \lim_{n \to \infty} \sqrt{n + a} * \sqrt{n + b} - n &= \\
          \lim_{n \to \infty} \sqrt{n(1 + \frac{a}{n})} * \sqrt{n(1 + \frac{b}{n})} - n &= \\
          \lim_{n \to \infty} n\sqrt{1 + \frac{a}{n}} * \sqrt{1 + \frac{b}{n}} - n &= \\
          \lim_{n \to \infty} n\Big(\sqrt{1 + \frac{a}{n}} * \sqrt{1 + \frac{b}{n}} - 1\Big)
        \end{aligned}
      \end{equation*}
    #+END_SRC
    Now, recall that $\lim_{n \to \infty} \sqrt{1 + \frac{a}{n}} = 1$, this gives us:
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation*}
        \begin{aligned}
          \lim_{n \to \infty} n\Big(\sqrt{1 + \frac{a}{n}} * \sqrt{1 + \frac{b}{n}} - 1\Big) &= \\
          \lim_{n \to \infty} n * \lim_{n \to \infty}\sqrt{1 + \frac{a}{n}} *
          \lim_{n \to \infty}\sqrt{1 + \frac{b}{n}} - \lim_{n \to \infty} 1 &= \\
          lim_{n \to \infty} n * (1 * 1 - 1) &= \\
          lim_{n \to \infty} n * 0 &= 0.
        \end{aligned}
      \end{equation*}
    #+END_SRC

*** Answer 7
    I know that this expression tends to negative infinity as $n$ tends to infinity
    simply because the numerator has a power of $n$ greater than the denominator and
    the greatest term in the denominator is negative.  But I couldn't find a way
    to prove this formally.

*** Answer 8
    I will show that the given sequence tentds to infinity.  Some notation first.
    I will use $H_n$ to denote the /nth/ harmonic numbers.  Let's
    at first, simplify the sum:
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation*}
        \begin{aligned}
          \sum_{k=1}^n \frac{k}{k + 1} &= \\
          \sum_{k=1}^n \frac{k + 1 - 1}{k + 1} &= \\
          \sum_{k=1}^n \frac{k + 1}{k + 1} - \frac{1}{k + 1} &= \\
          \sum_{k=1}^n \frac{k + 1}{k + 1} - \sum_{k=1}^n \frac{1}{k + 1} &= \\
          n - \sum_{k=1}^n \frac{1}{k + 1} &= \\
          n - \sum_{k=2}^{n+1} \frac{1}{k} &= \\
          n - H_{n+1} + 1
        \end{aligned}
      \end{equation*}
    #+END_SRC
    Now, plug this back into our formula:
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation*}
        \begin{aligned}
          \lim_{n \to \infty} \frac{n}{n + 1} (n - H_{n+1} + 1) &= \\
          \lim_{n \to \infty} \frac{n}{n + 1} (n - H_{n+1}) + \lim_{n \to \infty}1 &= \\
          \lim_{n \to \infty} \frac{n}{n + 1} (n - H_{n+1}) + 1 &= \\
          \lim_{n \to \infty} \Big( \frac{n^2}{n + 1} - \frac{n}{n + 1} H_{n+1} \Big) + 1 &= \\
          \lim_{n \to \infty} \Big( \frac{n^2 + 1}{n + 1} - \frac{1}{n + 1} -
          \frac{n}{n + 1} H_{n+1} \Big) + 1 &= \\
          \lim_{n \to \infty} \Big( \frac{n(n + 1)}{n + 1} - \frac{1}{n + 1} -
          \frac{n}{n + 1} H_{n+1} \Big) + 1 &= \\
          \lim_{n \to \infty} \Big( n - \frac{1}{n + 1} - \frac{n}{n + 1} H_{n+1} \Big) + 1 &= \\
          \lim_{n \to \infty} n - \lim_{n \to \infty} \frac{1}{n + 1} -
          \lim_{n \to \infty} \frac{n}{n + 1} H_{n+1} + 1 &= \\
          \lim_{n \to \infty} n - 0 - \lim_{n \to \infty} 1 * H_{n+1} + 1 &= \\
          \lim_{n \to \infty} n &= \infty.
        \end{aligned}
      \end{equation*}
    #+END_SRC
    The last step is allowed becasue for all harmonic numbers greater than one
    it holds that $n > H_{n+1}$.

** Problem 3
   Let $(a_n)$ be a sequence such that $\lim_{n \to \infty}(a_{n+1} - a_n) = 0$.
   1. Prove that if there exists a constant $c > 0$ s.t. for all $n$ 
      $\abs{a_n}\geq c$, then almost all elements of the sequence are either
      negative or positive.
   2. Show that the same doesn't hold for $\abs{a_n} > 0$.
   3. Show that if for all $n$ it holds that $\abs{a_n} \geq n$, then $(a_n)$
      converges in a general sense.

*** Answer 9
    First, observe that the definition gives us a Cauchy sequence.  Recall that
    Cauchy sequence is a sequence where intervals between subseqent members tend
    to zero as $n$ tends to infinity.  That said, from the definition of the
    limit, we can find $\epsilon < c$, such that almost all members of the
    sequence would be in the vicinity of $c$ no farther away than
    $\epsilon$. Thus, the sequence would converge to either a negative number or
    a positive number, but not zero.  Since almost all members of a sequence can
    be showed to be in a vicinity of a number other than zero, we have proved
    the claim.

*** Answer 10
    The example $(a_n)$ such that doesn't match the requirement from the previous
    question is, for example, $a_n = \frac{(-1)^n}{2n}$.  I.e. an alternating
    series where even members are positive and odd members are negative.  The
    general form of $a_{n+1} - a_n$ will thus look like this:
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation*}
        \lim_{n \to \infty}\Big(\frac{(-1)^{n+1}-2(-1)^n}{2n}\Big) = 0.
      \end{equation*}
    #+END_SRC
    
    It's easy to see that this limit is zero: the nominator is a constant term
    because one raised to any power is either one or negative one, while
    denominator is growing with $n$.  It is also easy to see that this is
    an alternating series, i.e. the sign alters with parity of $n$.

*** Answer 11
    Recall [[Answer 9]], where we used the fact that $(a_n)$ is described as a
    Cauchy sequence.  This is enough to show that this sequence converges in
    a general sense, whether the equation $\abs{a_n} \geq n$ holds or not
    is inconsequential.  Perhaps it's worth saying that the above requirement
    makes it explicit that the sequence converges to infinity if any of its
    members is positive, and negative infinity otherwise.

** Problem 4
   Given sequences $(a_n)$ and $(b_n)$ s.t. $\lim_{n \to \infty}(a_nb_n) = 0$,
   prove or disprove the following:

   1. Either $\lim_{n \to \infty}a_n = 0$ or $\lim_{n \to \infty}b_n = 0$.
   2. If $\lim_{n \to \infty}b_n = 1$, then there exists $N > 0$ s.t.
      $a_n < \frac{1}{2}$ for all $n > N$.
   3. If $\lim_{n \to \infty}b_n = 1$, then $\lim_{n \to \infty}a_n = 0$.
   4. If almost all members of $(b_n)$ are positive, then 
      $\lim_{n \to \infty}a_n \neq \infty$.
   5. If almost all members of $(b_n)$ are positive, then 
      $\lim_{n \to \infty}a_n = 0$.
   6. If there exists a constant $c > 0$ s.t. almost all $b_n \geq c$, then
      $\lim_{n \to \infty}a_n = 0$.

*** Answer 12
    The limit of a product is a product of limits (their existence is
    provisional).  This gives us an equation in two unknowns: $ab = 0$.
    From this equation follows that either $a$ or $b$ must be zero
    Thus the claim is true.

*** Answer 13
    As shown in [[Answer 12]], either one (or both) limits must be zero,
    thus if $\lim_{n \to \infty}a_n$ must be zero.  From definition of
    the limit, there must be an $\epsilon$, such that for any $N$, almost
    all $\abs{a_n - L} < \epsilon$, for $n > N$.  We can choose
    $\epsilon = \frac{1}{2}$, since $L$ (the limit of $(a_n)$) is zero
    the inequality becomes $\abs{a_n} < \frac{1}{2}$ since
    $a_n \leq \abs{a_n} < \frac{1}{2}$ the claim is true.

*** Answer 14
    The claim is true. This is simply a corollary of [[Answer 12]].

*** Answer 16
    This is not true.  Put $b_n = \frac{1}{n}$, the limit of $(b_n)$ is 0.  Even
    if $(a_n)$ is a divergent series, for example, $a_n = \sqrt{n}$ the limit of
    a product is still zero.

*** Answer 17
    Same example as [[Answer 16]].  Limit of $(a_n)$ isn't zero and yet the
    requirement is satisfied, thus the claim is false.

*** Answer 18
    Existence of lower bound greater than zero precludes $(b_n)$ from having
    zero as its limit.  Assuming that there are members of a sequence which
    are smaller than the lower bound is in direct contradiction with the
    bound definition.  Thus the limit of $(a_n)$ must be zero (follows from
    what we proved in [[Answer 12]]).  Thus the claim is true.
